name: ciga
dependencies:
    - python==3.6
    - jupyter 
    - jupyterlab
    - numpy
    - scipy
    - pandas
    - keras 
    - matplotlib
    - pydot
    - graphviz
    - Pillow
    - pip:
      - twilio
      - graphviz
      - tensorflow-gpu