name: ciga
dependencies:
    - python==3.6
    - jupyter 
    - jupyterlab
    - numpy
    - scipy
    - pandas
    - keras=2.1.5
    - tensorflow
    - matplotlib
    - pydot
    - graphviz
    - Pillow
    - sklearn
    - pip:
      - twilio
      - graphviz
